import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Arquitectura',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'arquitectura'}],
    },
    {
      type: 'category',
      label: 'Integraciones',
      items: [{type: 'autogenerated', dirName: 'integraciones'}],
    },
    {
      type: 'category',
      label: 'Guías',
      items: [{type: 'autogenerated', dirName: 'guias'}],
    },
  ],

  apiSidebar: [{type: 'autogenerated', dirName: 'api'}],
};

export default sidebars;
